name: Deploy to Minikube using GitHub Actions

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    name: Build Node.js Docker Image and Deploy to Minikube
    steps:
      - uses: actions/checkout@v2

      - name: Start minikube
        uses: medyagh/setup-minikube@master

      - name: Try the cluster!
        run: kubectl get pods -A

      - name: Build image
        run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          docker build -f ./Dockerfile -t devopshint/node-app:latest .
          echo "Verifying images:"
          docker images

      - name: Deploy to minikube
        run: kubectl apply -f k8s-node-app.yaml

      - name: Wait for pod to be ready
        run: |
          echo "Waiting for pod to be ready..."
          kubectl wait --for=condition=ready pod -l app=nodejs-app --timeout=90s

      - name: Port forward and test service
        run: |
          echo "Port forwarding service to localhost..."
          kubectl port-forward service/nodejs-app 8080:80 &
          sleep 5
          echo "Testing service endpoint:"
          curl http://localhost:8080

      - name: Check pod status
        run: kubectl get pods -o wide

      - name: Describe pods
        run: kubectl describe pods

      - name: View logs
        run: kubectl logs -l app=nodejs-app
